### ISSUE TITLE
Ontology page - multiple issues

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#104]
Testcase: iri-labels/efo-iri-labels.owl

<s> - [ ] Treeview incorrect - shows only 2 classes instead of 4. </s>
Compare OLS4
![image](https://user-images.githubusercontent.com/32327979/204846500-e1e3dcf0-7b3a-4095-84f1-5fee494d4c65.png)

vs Protege
![image](https://user-images.githubusercontent.com/32327979/204847103-d214a44b-17a7-423b-9be9-99aa54c71927.png)

- [ ]  Ontology annotations do not show at all.
See Protege:
![image](https://user-images.githubusercontent.com/32327979/204848253-c605057a-54f9-48bb-b0ba-17bfa788ee98.png)

- [ ] Multiple labels should not be shown: `has parthas_part` 
![image](https://user-images.githubusercontent.com/32327979/204849236-2526b44d-84ed-4d46-8362-81bc7d606656.png)

This happens because in OWL more than 1 label is given. I think we should use the first label. This should also be the first label for a given language when multi-lang is used. 
![image](https://user-images.githubusercontent.com/32327979/204849624-f3d28bc4-3ef1-4141-ae08-26e4fc0b68fb.png)

<s> - [ ] Number of classes is  incorrect. It shows 4 instead of 5.

- [ ] Number of terms is incorrect. It shows 6 instead of 7.  </s>

**Comment by jamesamcl** [comment]
> Number of classes is incorrect. It shows 4 instead of 5.
> Number of terms is incorrect. It shows 6 instead of 7.

Is this because aren't including owl:Thing?

**Comment by jamesamcl** [comment]
@serjoshua Out of these issues, only the label and ontology annotations are frontend. <s>The tree view might possibly be frontend but I will look into it. The counts are definitely backend and/or dataload.</s> (EDIT: issue found below)

**Comment by henrietteharmse** [comment]
> > Number of classes is incorrect. It shows 4 instead of 5.
> > Number of terms is incorrect. It shows 6 instead of 7.
> 
> Is this because aren't including owl:Thing?

No. 5 classes without Thing and 2 properties without topProperty.

**Comment by jamesamcl** [comment]
Both the tree view and count issues are caused by the same problem:

`OGMS_0000063` is a subClassOf `GO_0008150` which is not present in the OWL RDF file. Because it has a parent class, it is marked `isRoot: false`, so is expected to render as a child node in the tree view, but because the parent class is missing, this never happens.

Also, `GO_0008150` is not present in the counts, again because it is missing from the RDF.

If you reason over the ontology, `GO_0008150` is added because it is the target of a `subClassOf` relation. So this is actually an issue with ontologies that have not been reasoned (which we don't support loading in OLS4). We should address this by pre-reasoning the testcases.

**Comment by henrietteharmse** [comment]
@udp Ah! That makes sense! We do not need to prereason the testcases. I usually ensure that all terms are properly defined when I create testcases. Hence, I did not even think to check it here. But this testcase you created. I will fix it.

**Comment by henrietteharmse** [comment]
Fixed class definition gives the display! 
![image](https://user-images.githubusercontent.com/32327979/205015264-f171a134-1605-4985-9abf-3b1dd1f859ca.png)

**Comment by jamesamcl** [comment]
I separated the remaining issues into #125 and #126
