### ISSUE TITLE
Links should point back to hosting server

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#105]
Testcase: ./testcases/owl2-primer/subClassOf-intersectionOf.owl

![image](https://user-images.githubusercontent.com/32327979/204860747-e850fb37-5c60-4d28-8d1e-b658989829aa.png)

This shows the intersection under **Subclass of** perfectly, but the links should point back to the backend location. I.e. `subClassOf-intersectionOf#Man` points to "http://www.ebi.ac.uk/testcases/owl2primer/subClassOf-intersectionOf#Man" instead of "localhost/ols/owl2primer-subclassof-intersectionof/terms?iri=http://www.ebi.ac.uk/testcases/owl2primer/subClassOf-intersectionOf#Man".

Compare this with current OLS: [EFO_0001421](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001421):
![image](https://user-images.githubusercontent.com/32327979/204862925-9166f88e-7274-4f41-be7b-7e2a289f9bae.png)

If you click on "part of" it navigates to [part of](https://www.ebi.ac.uk/ols/ontologies/efo/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050), it does not go to "http://purl.obolibrary.org/obo/BFO_0000050".

**Comment by jamesamcl** [comment]
The challenge here is knowing what to make a link:

* Sometimes the entity IRI is defined in the same ontology we are looking at. This is the easy case; we can just link to e.g. `<OLS4>/ontologies/<ontology>/entities/<iri>`.

* Sometimes the entity is defined in a different ontology. In many cases it is also copied into the ontology we are looking at but not always. Then we would need to link across ontologies, but to do so we need to work out in which ontologies the term is defined.

* Sometimes the entity is not defined anywhere, in which case we shouldn't create a link at all if it is going to be a 404 when you click it.

I see two possible approaches to making the links:

1. Get the information at resolution time, so if you click a link it goes to something like `/redirectToIri/<iri>` which queries the DB to find out where to take you to. Caveat is then we have to make everything a link because we don't know what's going to be a 404. I therefore don't like this approach.

2. Make the information available at the render time of the page. For example we could expand the current `iriToLabels` map to be a more general `referencedEntities` (or something) with both the labels (as we have currently) and the ontology each IRI is defined in. So for example, this which we have at the moment:2. 

```json
"iriToLabels": {
    "http://purl.obolibrary.org/obo/RO_0001000": ["derives from"]
}
```

would become something like:

```json
"referencedEntities": {
    "http://purl.obolibrary.org/obo/RO_0001000": {
        "labels": ["derives from"],
        "definingOntology": "ro",
        "locallyDefined": true
    }
}
```

where `locallyDefined` indicates if this ontology has a copy of it which we should (controversially :D) link to instead.

**Comment by jamesamcl** [comment]
I've made a branch which replaces `iriToLabels` with `referencedEntities` because (1) I think it's a much better name for it and (2) it means we can add more fields than just the labels in the future. 

For now I'm going to turn anything that's present in `referencedEntities` into a link within the ontology. We can worry about links between ontologies afterwards.
