### ISSUE TITLE
Equivalent classes do not show.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#108]
Testcase: testcases/owl2-primer/equivalent-intersectionOf.owl

![image](https://user-images.githubusercontent.com/32327979/205104286-caac6a98-187a-4d7b-933b-f7eb9d567f25.png)

When `Mother` is selected under _Class Relations_ should be another subheading **Equivalent to** similar to **Subclass of**, stating _Woman and Parent_.

See  for example [http://purl.obolibrary.org/obo/CEPH_0000288](https://www.ebi.ac.uk/ols/ontologies/ceph/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCEPH_0000288)
![image](https://user-images.githubusercontent.com/32327979/205107329-8bc78270-6269-4b66-9c1b-ec82cc6acf56.png)

**Comment by henrietteharmse** [comment]
In Neo4J, `Mother` is stored and has the relevant bit:

```
"http__//www.w3.org/2002/07/owl#equivalentClass": [
      "http://www.ebi.ac.uk/testcases/owl2primer/equivalent-intersectionOf.owl#Parent",
      "http://www.ebi.ac.uk/testcases/owl2primer/equivalent-intersectionOf.owl#Woman"
],
```

**Comment by jamesamcl** [comment]
@serjoshua To clarify, this is not related to Neo4j as none of the fields in Neo4j or Solr are used anywhere in the API responses or in the frontend.

You can read the `http://www.w3.org/2002/07/owl#equivalentClass` property from the JSON the frontend already retrieves from the API.

**Comment by serjoshua** [comment]
Yup, this is indeed a frontend issue. I still need to implement this.

**Comment by henrietteharmse** [comment]
More tests in this regard are in /testcases/owl2-primer/

equivalentClass.owl
equivalent-intersectionOf-complementOf.owl
equivalent-propertyRestriction-allValuesFrom.owl
equivalent-propertyRestriction-hasSelf.owl
equivalent-propertyRestriction-someValuesFrom.owl
equivalentClass-collection.owl

These are good tests for testing related classes as well.

**Comment by serjoshua** [comment]
![Screen Shot 2023-01-06 at 11 38 08 AM](https://user-images.githubusercontent.com/25520595/211006404-827821da-d5e9-4dd0-bb97-1d7309fe7487.png)
![Screen Shot 2023-01-06 at 11 38 13 AM](https://user-images.githubusercontent.com/25520595/211006428-7c09450c-3d05-4d1f-92d1-b05e8132f013.png)
![Screen Shot 2023-01-06 at 11 38 22 AM](https://user-images.githubusercontent.com/25520595/211006443-bada4c2d-dd93-4232-acd5-876c3c90501e.png)

Implemented display of equivalent relations but one example is not symmetric? The backend doesn't return an equivalent class for Person but for Human it does. I just thought it is weird. It also happens for the equivalent property example. (Yes, we handle equivalent properties too now.)

![Screen Shot 2023-01-06 at 11 39 36 AM](https://user-images.githubusercontent.com/25520595/211006856-76311e1b-0988-4a9e-81d3-87a62da7b032.png)

Also, we still experience discrepancy in the no. of classes count. This equivalent example ontology says it has 2 classess but only displays one. I just thought you should know. The root entities API also returns just one.

Anyway, the frontend part has been implemented. Let me know if you like to track issues using this ticket @udp. Otherwise, I'll close it. Thanks!

**Comment by jamesamcl** [comment]
I fixed this in the dataload but would like you to test with the frontend @serjoshua before we close the issue

**Comment by jamesamcl** [comment]
nvm I checked and it's fixed!
