### ISSUE TITLE
OLS4 Ontologies page missing last loaded date

### ISSUE THREAD

**Issue by helenp** [EBISPOT/ols4#187]
This is missing compared to OLS3. I find the last loaded page useful as a proxy for last updated.
And when I get to the ontology page I also want the version higher up the list.

**Comment by jamesamcl** [comment]
Version is now right below the ontology title rather than in the properties:

<img width="1079" alt="Screenshot 2023-02-28 at 02 30 37" src="https://user-images.githubusercontent.com/454895/221738000-50e72deb-1485-49c6-9945-4b5879dd2a6f.png">

Last loaded dates are implemented but won't be visible until the next dataload has completed.
