### ISSUE TITLE
ObjectProperty tree display broken

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/ols4#236]
Property tree failing to display ancestors (by subPropertyOf) and crashes when trying to fold out descendants, e.g. 

![image](https://user-images.githubusercontent.com/112839/221835571-75b980c9-03b7-40c7-98c6-cae422e716d6.png)

This works fine in OLS3

![image](https://user-images.githubusercontent.com/112839/221836109-4c07a7ab-4d98-44ec-80b4-cac0200ef4ca.png)

**Comment by jamesamcl** [comment]
Ah that's annoying, it definitely used to work. Must be a regression of the recent tree updates. I will look into it.

**Comment by dosumis** [comment]
>  it definitely used to work. 

Thought I remembered it working previously

**Comment by jamesamcl** [comment]
Strangely this seems to work for me at the moment:

https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0013001

Showing ancestors:

<img width="1060" alt="Screenshot 2023-02-28 at 21 37 34" src="https://user-images.githubusercontent.com/454895/221986385-acec008b-1686-4391-8a4d-d53a3a8966de.png">

Expanding the node:

<img width="411" alt="Screenshot 2023-02-28 at 21 37 41" src="https://user-images.githubusercontent.com/454895/221986422-dcd15aee-a509-4a55-a916-da44674419aa.png">

I wonder if there was an issue with Neo4j (which is where ancestors/children come from; everything else in the page comes from Solr). I really want errors to be displayed by the frontend rather than hanging indefinitely (#224).
