### ISSUE TITLE
Ontology terms from foreign ontologies don't show up in filtered search results?

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/ols4#282]
I did a search for glaucoma and limited the results to EFO and it only returned 5 results: 
![image](https://user-images.githubusercontent.com/4139843/225880586-aacf6fa7-2a57-4b6f-87d6-1bd8414bad71.png)

However, EFO does have a glaucoma term that is sourced from MONDO:
![image](https://user-images.githubusercontent.com/4139843/225880828-b97ada50-f247-4db5-a5f7-577730496821.png)

It's a common use case for curators to look for search for terms within a specific ontology and the current results don't show all of them. Is this the expected behaviour? It works correctly in OLS3:
![image](https://user-images.githubusercontent.com/4139843/225881691-0ef4576f-6ff0-4f5a-a33b-e12f7e37ef7b.png)

**Comment by smlmbrt** [comment]
I think this might have to do with "canonical definitions only" being selected by default in OLS4 - does this mean only terms originating from that ontology? This will likely be confusing to non-experts, suggest making it identical to OLS3 and not activating that filter by default.

**Comment by jamesamcl** [comment]
Yes it is because "canonical definitions only" is checked. We can look at changing the default but the OLS3 behaviour is also arguably confusing as the same term appears hundreds of times in some cases when it only has 1 canonical definition.

Maybe there's a compromise like showing all the results by default but highlighting the defining one; or hiding the other results but adding a link with something like "57 non-canonical definitions hidden" that shows the others.

**Comment by smlmbrt** [comment]
> Maybe there's a compromise like showing all the results by default but highlighting the defining one

This seems like a good option that would complement the old behaviour. 

<br>

> hiding the other results but adding a link with something like "57 non-canonical definitions hidden" that shows the others

I also like that, but would need to be optimised for the case where I want to filter for terms in a specific ontology (EFO),  and then view its placement within that tree.
