### ISSUE TITLE
[OLS4 feedback] - ontology page display

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/ols4#289]
https://www.ebi.ac.uk/ols4/ontologies/duo

 - list view should include IDs alongside labels (or be customizable)
 - ontology information box on right hand side:
      - properties should be displayed by their label instead of URIs (eg "creator" instead of "http://purl.org/dc/elements/1.1/creator")
      - it would be great to recognize and hyperlink webpages, eg https://github.com/EBISPOT/DUO/blob/master/README.md#contributions
 - I love the counts!
 - if possible an option to 'expand all' would be great instead of having to expand hierarchy one at a time

**Comment by jamesamcl** [comment]
Thanks Melanie!

- [x] properties should be displayed by their label instead of URIs (eg "creator" instead of "http://purl.org/dc/elements/1.1/creator")
- [x] it would be great to recognize and hyperlink webpages, eg https://github.com/EBISPOT/DUO/blob/master/README.md#contributions
- [x] list view should include IDs alongside labels (or be customizable)
- [ ] if possible an option to 'expand all' would be great instead of having to expand hierarchy one at a time

**Comment by henrietteharmse** [comment]
Closing this as most have been completed and issue created for outstanding issue.
