### ISSUE TITLE
Blank swagger documentation page

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/ols4#319]
Following the link from Help > Using the API > Swagger documentation opens a blank page https://www.ebi.ac.uk/ols4/swagger-ui/index.html

**Comment by jamesamcl** [comment]
The routing is fixed so it routes to swagger, but it returns the API for a pet store.

<img width="1504" alt="Screenshot 2023-05-12 at 12 44 04" src="https://github.com/EBISPOT/ols4/assets/454895/f2971374-8b47-4230-8218-9f84bd95cf52">

**Comment by giraygi** [comment]
@udp @serjoshua 

This is how it looks like in my local installation. I have never encountered the petstore.

![Screenshot from 2023-05-15 11-15-36](https://github.com/EBISPOT/ols4/assets/48091473/0f6fe3f3-0232-414a-8fc5-7e0dcd0bd55e)

**Comment by EliotRagueneau** [comment]
Hi, 

I noticed the same issue so I came here: the pet store is just the default configuration, a sample for when your server is not yet fully configured.

I'm not quite sure that applies here, but I think we had similar issues in Reactome, because of the context-path when deployed, it was basically pointing to the wrong thing, we fixed that with this snippet:
https://github.com/reactome/content-service/blob/261bb77e264f9ac9b19d1ecade0eb8ef7d7f143e/src/main/java/org/reactome/server/service/config/SwaggerConfig.java#L21-L34

And more specifically this part:
```java
new OpenAPI().addServersItem(new Server().url(context.getContextPath()));
```

Not sure it's gonna fix your issue, but maybe worth trying :D

**Comment by jamesamcl** [comment]
Thanks @EliotRagueneau !

@serjoshua can you see if this works? Unassigning myself as the firewall changes are done.

**Comment by StephJones87** [comment]
I am trying to use OLS API

When I start on the homepage - https://www.ebi.ac.uk/ols4/

And click 'help', the next option is to click swagger documentation.

Clicking 'swagger documentation' - takes me to the petstore page as above?

**Comment by jamesamcl** [comment]
It's accessible at https://www.ebi.ac.uk/ols4/swagger-ui/index.html now ; just need to update links in the docs
