### ISSUE TITLE
HP/HPI mess

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#345]
We added an internationalised version of HPI very early in development to test multilang. It seems to work reasonably well, but having 2 ontologies with the same base_uri means every occurrence of a HP term in OLS currently links to both "HP" and "HPI" as being canonical.

I think we should remove HPI from OLS4 production until it's merged into HP itself. If any further testing of multilang is required it should happen in a testing OLS instance.

@matentzn fyi

**Comment by matentzn** [comment]
I think the best way is for OLS to load HPO international only. That is, overwrite the `purl` field for `hp` to use the `http://purl.obolibrary.org/obo/hp/hp-international.owl`. Do you have any concerns about that?

**Comment by jamesamcl** [comment]
@matentzn I have no concerns about that if there aren't any concerns from HP.

**Comment by matentzn** [comment]
Yes, as a member of the HPO consortium I make this executive decision now: 

1. Use `http://purl.obolibrary.org/obo/hp/hp-international.owl` as instead of the canonical `http://purl.obolibrary.org/obo/hp.owl`. The international edition is _literally_ the hp.owl version plus the translations, nothing else.
2. Remove hpi

**Comment by jamesamcl** [comment]
Deployed
