### ISSUE TITLE
search additional synonym types

### ISSUE THREAD

**Issue by balhoff** [EBISPOT/ols4#358]
When searching an ontology for a term, I would expect to find text matches across all OBO synonym types (exact, narrow, broad, related). 

On this page: https://www.ebi.ac.uk/ols4/ontologies/uberon if I type `head and neck` in the search bar I see five terms in the autocomplete, but not the term that has exactly that text in a "related synonym": [craniocervical region](http://purl.obolibrary.org/obo/UBERON_0007811).

If I do a general OLS search: https://www.ebi.ac.uk/ols4/search/head%20and%20neck and restrict to Uberon using the side checkbox, I have 418 results but none of them is [craniocervical region](http://purl.obolibrary.org/obo/UBERON_0007811).

In Uberon this text is related to the term with [has_related_synonym](http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym), which I guess isn't currently being used for searches. Thanks!

**Comment by ghost** [comment]
Boosting this issue.

**Please also configure CL to return search results when exact, narrow, broad or related synonyms are used to search.** The lack of related synonyms generating appropriate search results in OLS4 was noted [here](https://github.com/EBISPOT/ols4/issues/309). The issue was closed, but the **related** synonym search does not appear to have been implemented.

CL is also working to update all synonyms which are abbreviations to be **related** synonyms. Currently synonyms are inconsistently annotated as exact or related. E.g., see https://github.com/obophenotype/cell-ontology/issues/1925. 
Please ensure search strings that are related synonyms will be used to generate applicable search results so these terms will not be dropped from the search results.

**Comment by jamesamcl** [comment]
For OLS devs: seems to be a dataload issue as there is no `synonym` field in https://www.ebi.ac.uk/ols4/api/v2/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0007811

Looking at the SynonymAnnotator https://github.com/EBISPOT/ols4/blob/dev/dataload/rdf2json/src/main/java/uk/ac/ebi/owl2json/annotators/SynonymAnnotator.java I think we are just missing some predicates. These can be overridden by the config but we need sensible defaults.

**Comment by henrietteharmse** [comment]
@balhoff This issue is now fixed as far I can see. Let me know if you still find issues in this regard!
