### ISSUE TITLE
Provide a single redirect for term browsers

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/ols4#378]
I am trying to redirect OBO PURLs to OLS:

https://github.com/OBOFoundry/purl.obolibrary.org/pull/922/files

However, right now I cant - I need a single URL to access without knowing whether something is property or a class. 

While

https://www.ebi.ac.uk/ols4/ontologies/bspo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCARO_0000000?lang=en

also works when i replace `classes` with `terms`:

https://www.ebi.ac.uk/ols4/ontologies/bspo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCARO_0000000?lang=en

This does not work:

https://www.ebi.ac.uk/ols4/ontologies/bspo/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBSPO_0000107?lang=en

changed to:

https://www.ebi.ac.uk/ols4/ontologies/bspo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBSPO_0000107?lang=en

What redirect should I choose if I don't know if an ID corresponds to a property or a class?

**Comment by jamesamcl** [comment]
We should add /entities/ which retrieves the type and redirects accordingly.

**Comment by serjoshua** [comment]
Having a single redirect like /entities would be really nice but, just a suggestion, why not take advantage of /terms and use it as our primary and singular redirect instead of introducing a new endpoint /entities?

Right now:
- /terms redirects solely to /classes

Moving forward:
- /terms retrieves type and redirects accordingly: /classes, /properties or /individuals

This is assuming that /terms endpoint is provided with a full IRI either thru path or passed as a path parameter.

**Comment by jamesamcl** [comment]
I think @henrietteharmse once told me that individuals aren't considered terms, but colloquially they are and since it's just a backwards compatibility redirect I think it's fine to handle everything through the terms URL.

We should also support "entities" as it's the official OWL terminology from the spec. But they can point to the same place.

**Comment by matentzn** [comment]
@serjoshua - can I bump the importance of this a bit? Many ontologies don't have working redirects right now, which is causing confusion and support overhead..

**Comment by serjoshua** [comment]
We already implemented a way to redirect /terms and /entities to their corresponding type: /classes, /properties or /individuals.

https://www.ebi.ac.uk/ols4/ontologies/bspo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBSPO_0000107?lang=en
and
https://www.ebi.ac.uk/ols4/ontologies/bspo/entities/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBSPO_0000107?lang=en

will both redirect to
https://www.ebi.ac.uk/ols4/ontologies/bspo/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBSPO_0000107?lang=en

Provided that a correct encoded IRI is passed along in the path.

**Comment by matentzn** [comment]
Thank you @serjoshua
