### ISSUE TITLE
fewer search results in ols4 than ols3

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#386]
OLS3

https://www.ebi.ac.uk/ols/api/search?q=diabetes&ontology=efo,mondo

OLS4

https://www.ebi.ac.uk/ols4/api/search?q=diabetes&ontology=efo,mondo

**Comment by serjoshua** [comment]
This is the old endpoint:
[https://www.ebi.ac.uk/ols/api/select?type=class&ontology=edam&sort=label%20desc&row[…]00&q=data&allChildrenOf=http://edamontology.org/operation_0004](https://www.ebi.ac.uk/ols/api/select?type=class&ontology=edam&sort=label%20desc&rows=1000&q=data&allChildrenOf=http://edamontology.org/operation_0004)

and this a the same query string, but using ols4 instead of 3:
[https://www.ebi.ac.uk/ols4/api/select?type=class&ontology=edam&sort=label%20desc&ro[…]00&q=data&allChildrenOf=http://edamontology.org/operation_0004](https://www.ebi.ac.uk/ols4/api/select?type=class&ontology=edam&sort=label%20desc&rows=1000&q=data&allChildrenOf=http://edamontology.org/operation_0004)
Notice that the older API returns 36 records, where as the newer one returns 27

Copying an issue reported by Mahfouz Shehu for documentation purposes. Might be related.

**Comment by jamesamcl** [comment]
I think our Solr index has a subtly different configuration to OLS3. Will look more into it tomorrow.

**Comment by jamesamcl** [comment]
I think this is possibly because OLS4 does not currently have a solr index for `annotations_trimmed` like OLS3 did, so the annotations are not being searched.

OLS3 implementation:

https://github.com/EBISPOT/OLS/blob/04f73e8aaf52ab2dc6014845b35f9feef14d1799/solr/solr-5-config/ontology/conf/schema.xml#L173-L177

**Comment by henrietteharmse** [comment]
Example from #407  
I've been trying to migrate our pipelines to OLS4 and am running into a discrepancy in the behaviour for one of the API endpoints:
[https://www.ebi.ac.uk/ols/api/search?ontology=chebi&q=allopurinol](https://www.ebi.ac.uk/ols/api/search?ontology=chebi&q=allopurinol)
vs.
[https://www.ebi.ac.uk/ols4/api/search?ontology=chebi&q=allopurino](https://www.ebi.ac.uk/ols4/api/search?ontology=chebi&q=allopurinol)

**Comment by henrietteharmse** [comment]
@serjoshua  If this is working this should return over 400 results:
https://www.ebi.ac.uk/ols4/api/search?q=diabetes&ontology=efo,mondo

**Comment by henrietteharmse** [comment]
@serjoshua To test this on dev: 
This should return more that about 400 results: https://www.ebi.ac.uk/ols4/api/search?q=diabetes&ontology=efo,mondo

**Comment by serjoshua** [comment]
Tested the backend changes in my local and it seems like it is returning more results now compared to what we have in production:

Local: 508 terms
<img width="550" alt="Screen Shot 2023-08-15 at 4 02 54 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/f5e3a080-dff4-4807-b074-bc173234e071">

OLS3: 409 terms
<img width="572" alt="Screen Shot 2023-08-15 at 4 03 09 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/231dc032-2b43-47b3-b7d8-6586c38586b5">

OLS4: 281 terms
<img width="548" alt="Screen Shot 2023-08-15 at 4 03 37 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/efd21f10-db98-4361-9f67-8e60cb8f36ca">

**Comment by henrietteharmse** [comment]
This should be fixed now!
