### ISSUE TITLE
Error when accessing Ontologies from OLS3

### ISSUE THREAD

**Issue by renatocjn** [EBISPOT/ols4#388]
Hi,
I recently did the migration of links from identifiers.org and replacing the ols4 on the URL worked for most of our namespaces but it failed for some, these are the current links that we use and that work with ols URLs but don't work with ols4 URLs. Not sure if this is related to the fix done for #351. Could you have a look?

- https://www.ebi.ac.uk/ols/ontologies/bao/terms?obo_id=BAO:0002989
- https://www.ebi.ac.uk/ols/ontologies/teddy/terms?short_form=TEDDY_0000066
- https://www.ebi.ac.uk/ols/ontologies/obi/terms?obo_id=OBI_0000070
- https://www.ebi.ac.uk/ols/ontologies/edam/terms?short_form=data_1664
- https://www.ebi.ac.uk/ols/ontologies/vario/terms?obo_id=VariO:0294
- https://www.ebi.ac.uk/ols/ontologies/mamo/terms?short_form=MAMO_0000026
- https://www.ebi.ac.uk/ols/ontologies/eo/terms?obo_id=EO:0007404
- https://www.ebi.ac.uk/ols/ontologies/ordo/terms?short_form=Orphanet_C023
- https://www.ebi.ac.uk/ols/ontologies/probonto/terms?short_form=PROB_c0000005
- https://www.ebi.ac.uk/ols/ontologies/nmrcv/terms?short_form=NMR:1000003

Best.

**Comment by serjoshua** [comment]
Good day Renato,

Upon checking all of the URLs, this is what we found out.
- term exists in OLS4 but needs fixing the page, you could search it though
https://www.ebi.ac.uk/ols/ontologies/bao/terms?obo_id=BAO:0002989
- ontology exists in OLS4 config but did not load in OLS4
https://www.ebi.ac.uk/ols/ontologies/teddy/terms?short_form=TEDDY_0000066
- term exists in OLS4 but needs fixing the page, you could search it though
https://www.ebi.ac.uk/ols/ontologies/obi/terms?obo_id=OBI_0000070
- term does not exist in previous OLS and OLS4
https://www.ebi.ac.uk/ols/ontologies/edam/terms?short_form=data_1664
- ontology exists in OBO config but did not load in OLS4
https://www.ebi.ac.uk/ols/ontologies/vario/terms?obo_id=VariO:0294
- ontology exists in OBO config but did not load in OLS4
https://www.ebi.ac.uk/ols/ontologies/mamo/terms?short_form=MAMO_0000026
- ontology exists in OBO config but did not load in OLS4
https://www.ebi.ac.uk/ols/ontologies/eo/terms?obo_id=EO:0007404
- term did not load in OLS4
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?short_form=Orphanet_C023
- ontology exists in OLS4 config but did not load in OLS4
https://www.ebi.ac.uk/ols/ontologies/probonto/terms?short_form=PROB_c0000005
- term exists in OLS4 but needs fixing the page, you could search it though
https://www.ebi.ac.uk/ols/ontologies/nmrcv/terms?short_form=NMR:1000003

So for some URLs, we just have problem calling our APIs but you could search the term in OLS4. And then some terms and ontologies are just not loading properly, we are on it.

For data_1664, we just want to verify if it is an actual term you use since I cannot find it in the previous version of OLS.

**Comment by henrietteharmse** [comment]
@serjoshua Can you please follow up with each of these and resolve them. I.e., 
1. Follow up why Teddy is not in OLS4. 
2. Follow up on these OBO ontologies are not loading. 
3. Follow up on why specific terms did not load.

**Comment by renatocjn** [comment]
Hi, just to give more context on data_1664, this is a term of EDAM marked as obsolete. Perhaps this is why you couldn't find it. We use it as an example ID of our EDAM namespace. We should probably replace it with something that isn't obsolete though.
- https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Fdata_1664
- https://bioportal.bioontology.org/ontologies/EDAM?p=classes&conceptid=data_1664

**Comment by jamesamcl** [comment]
The term is there, you just can't search for it unless you check "include obsolete terms":

https://www.ebi.ac.uk/ols4/ontologies/edam/classes/http%253A%252F%252Fedamontology.org%252Fdata_1664

**Comment by serjoshua** [comment]
Revisiting this issue, below are corresponding OLS4 pages that work:

1. https://www.ebi.ac.uk/ols4/ontologies/bao/classes?obo_id=BAO:0002989
2. https://www.ebi.ac.uk/ols4/ontologies/teddy/classes?short_form=TEDDY_0000066
3. https://www.ebi.ac.uk/ols4/ontologies/obi/classes?short_form=OBI_0000070
4. https://www.ebi.ac.uk/ols4/ontologies/edam/terms?iri=http://edamontology.org/data_1664
5. VARIO still failing, refer to #453 
6. MAMO still failing, refer to #453 
7. EO still failing, refer to #453 
8. ORDO is fine but there is still some difficulty accessing or finding the term
9. https://www.ebi.ac.uk/ols4/ontologies/probonto/terms?short_form=PROB_c0000005
10. https://www.ebi.ac.uk/ols4/ontologies/nmrcv/classes?obo_id=NMR::1000003

If you feel strongly about (8), we recommend raising a separate ticket. As for the failing ontologies, we might need help reaching out to proper channels to fix the ontologies. Another option would be to figure out some workaround. Eitherway, we recommend referring to issue #453 for now.
