### ISSUE TITLE
Legacy autocomplete widget broken

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#401]
This definitely used to work with OLS4 but seems to be broken by changes in the select API.

See also https://github.com/obophenotype/cell-ontology/issues/2039#issuecomment-1604275979

**Comment by jamesamcl** [comment]
tagging @hkir-dev

**Comment by hkir-dev** [comment]
Now https://github.com/EBISPOT/OLS-autocomplete/blob/master/build/ols-autocomplete.js is failing due to response data's change in the OLS4. Some observed differences are:
- `responseHeader.params.q` (searched term) is missing in the new API
- `highlighting` field is missing in the new API
- `response.docs.ontology_prefix` field is missing in the new API
- `short_form`, `label`, `obo_id` are now string list, while they were string previously.

https://www.ebi.ac.uk/ols/api/select?q=gaba&ontology=cl
https://www.ebi.ac.uk/ols4/api/select?q=gaba&ontology=cl
