### ISSUE TITLE
[OLS4] "Search in ..." feature not filtering ontologies in the subsequent search

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/ols4#419]
Using OLS4 UI, when inside of a term (e.g. [``EDAM:1915``](https://www.ebi.ac.uk/ols4/ontologies/edam/classes/http%253A%252F%252Fedamontology.org%252Fformat_1915)), the search box displays ``Search in ...``, where ``...`` is the ontology of the term:
![image](https://github.com/EBISPOT/ols4/assets/77288380/b0fbf587-4350-43e3-bb77-ae0eee32765e)

The expected behaviour (and so was in OLS3) is that the subsequent search would filter by the displayed ontology, but instead the search is unfiltered by ontologies. In this example, the ``EDAM`` ontology is not ticked as a filter:
![image](https://github.com/EBISPOT/ols4/assets/77288380/49b8daa6-d574-49f9-83df-989f5eb51a2f)

**Comment by henrietteharmse** [comment]
@M-casado Thanks for logging this. Our thinking is that this is expected behaviour and an improvement over OLS3. When you are on an ontology like EDAM and do a search on that page, the search is constrained to that ontology. See:
![image](https://github.com/EBISPOT/ols4/assets/32327979/3f78ff14-0e54-4daf-a682-26383ac6c36b)
Clicking on an auto-suggest term, i.e. BAM in this case, will keep you in EDAM.
Selecting "Search OLS ..." will allow you to search other ontologies, not only EDAM. Selecting EDAM here will bring back the same results as when searching on the EDAM page.  

Does that make sense?

**Comment by henrietteharmse** [comment]
Ah! But when you click on Search button it should have the ontology checked!

**Comment by M-casado** [comment]
Hi @henrietteharmse, as you mentioned:
> When you are on an ontology like EDAM and do a search on that page, the search is constrained to that ontology

This is what I meant that should happen and I noticed that didn't. As you stated in your last comment, I meant that the ontology is not checked in the ulterior search when you click on search and want to restrict it to the ontology.

**Comment by henrietteharmse** [comment]
Related #302
