### ISSUE TITLE
Blank page for RO:0001025 'located in'

### ISSUE THREAD

**Issue by aleixpuigb** [EBISPOT/ols4#426]
OLS4 is working normally, but when I look for [RO:0001025 'located in'](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0001025) I get a blank page. I haven't encountered this problem with any other term so far.

**Comment by jamesamcl** [comment]
@henrietteharmse JS error here

![Screenshot 2023-07-20 at 13 03 44](https://github.com/EBISPOT/ols4/assets/454895/5ebb2623-111e-4899-a26e-53c1a2324259)

Not really sure what the purpose of using part of the annotation value as part of the key is when a random string is being appended anyway (making the key useless for react). 

It doesn't work because not all values are strings: this one is an intersectionOf.

You can debug it by running the frontend locally against prod OLS4 api.

**Comment by serjoshua** [comment]
I apparently added map sorting (to sort some annotations alphabetically) in this component and I have to give keys to each list item. What I didn't anticipate is that `annotation.value` could be an object. I also added random string just to make the JS warning go away with the not-unique annotations. Rendering the annotation has no problem though since we have `renderAnnotation()` function that could handle `annotation.value` as JSON object or as string.

I added `toString()` after `annotation.value` for the key prop since it's just for the list item element identification (key).
