### ISSUE TITLE
use go-plus for Gene Ontology

### ISSUE THREAD

**Issue by balhoff** [EBISPOT/ols4#476]
Hi, we (GO) would like to have go-plus be the browsable version of GO in OLS. This has the same topology for GO terms but includes axioms referencing external ontologies like ChEBI and Uberon. The PURL is `http://purl.obolibrary.org/obo/go/extensions/go-plus.owl`. Would this be possible? Thanks!

Issue at GO: https://github.com/geneontology/go-ontology/issues/19440

**Comment by serjoshua** [comment]
Since GO is obtained from OBO Foundry [configuration](https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/_config.yml), any GO-related updates should be done there. Looking at it, we have `ontology_purl: http://purl.obolibrary.org/obo/go.owl` at the moment. For OLS to use the new PURL, a change request to OBO Foundry configuration should be raised.

**Comment by matentzn** [comment]
@serjoshua this case may happen more often in the future; this is not a matter of PURLs changing (go will want their default PURLs to be what they are) but a matter of "which version of the ontology is best suited for display in a term browser" - which may be different from the default version. 

if we overwrite:

https://github.com/EBISPOT/ols4/blob/dev/ebi_ontologies.json

with `ontology_purl: http://purl.obolibrary.org/obo/go/go-base.owl` owl, would that file be loaded? (While the rest of the ontology metadata remains the same and is obtained from OBO)?

**Comment by balhoff** [comment]
Thanks @matentzn, that's right. This is one of our alternative products in the OBO config: http://obofoundry.org/ontology/go.html

**Comment by serjoshua** [comment]
Apologies if I answered without knowing the actual use case. We could definitely do an OLS-specific override to use a different PURL from the one provided in OBO Foundry. Changes will be made available after the next data release. Unfortunately, that won't happen until next week the earliest because of the maintenance work in our servers.

**Comment by matentzn** [comment]
Sounds good. Next week is great! Will you update the config and link the update to this ticket?

**Comment by balhoff** [comment]
Thanks @serjoshua, that sounds great.

**Comment by serjoshua** [comment]
We will keep you posted and link any changes to this ticket.

**Comment by serjoshua** [comment]
New data has been released using GO's new PURL

![Screen Shot 2023-08-22 at 4 25 15 PM](https://github.com/EBISPOT/ols4/assets/25520595/7a97288b-94cf-499d-9369-a03f6effec97)

**Comment by balhoff** [comment]
Thank you @serjoshua, looks good!
