### ISSUE TITLE
Clarification on endpoint structure documentation

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/ols4#527]
Hi!,

As I was browsing the docs here, https://www.ebi.ac.uk/ols4/help, I got confused about the structure of some of the endpoints as they did not seem to match the provided examples (or maybe I am missing something):

- Parent/child relationships for terms: 
  In `GET /api/ontologies/{ontology}/parents?id={id}`, the `parents` component is actually variable, is it not? Admits alternative values such as: `children`, `ancestors`, `descendants`, `hierarchicalDescendants` or `hierarchicalAncestors`?
- Other related terms: The indicated structure `GET /api/ontologies/{ontology_id}/terms/{term_iri}/{property_iri}` does not seem to be followed in the examples, e.g. `http://www.ebi.ac.uk/ols4/api/terms?short_form=EFO_0000001`.
- Retrieve an individual: `GET /api/ontologies/{ontology}/individuals/{iri}` is not followed in the examples, e.g. there is no place for the ontology field in the examples, e.g. `http://www.ebi.ac.uk/ols4/api/individuals?iri=http://purl.obolibrary.org/obo/IAO_0000125`.

And is there any documentation on the structure of the responses (i.e. the meaning of each variable)?

EDIT: I inadvertently added the bug label.

**Comment by serjoshua** [comment]
Hello @ramiromagno,

To answer your questions:

1. Yes, it is variable. Instead of explicitly stating it in the _Request structure_ part, we just decided to give examples.
2. and 3. Both of these sections do not have sample requests, it is a bit confusing but the sample requests you are referring are actually sample requests for the next section.

What we are going to do is that we will be updating the page a bit to make clear difference among sections and at the same time, I will add _Sample requests_ for the sections you mentioned.

We are planning on adding a Swagger documentation page for our APIs but unfortunately we are still in the process of fixing it.

**Comment by ramiromagno** [comment]
Hi Josh,

Thank you for the clarification!

I guess it makes sense then to leave the issue open until you release the new Swagger documentation.

**Comment by serjoshua** [comment]
We have updated the documentations page to add some sample requests and responses. As for the Swagger documentation issue, please refer to #319. Closing this ticket.
