### ISSUE TITLE
OLS4 terms resource returns 404 for specific term

### ISSUE THREAD

**Issue by famaladoss** [EBISPOT/ols4#547]
> curl 'https://www.ebi.ac.uk/ols4/api/ontologies/GAZ/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGAZ_00240693' \
>   -H 'Accept: application/json' \
>   --compressed

return 404 status. But the same resource returns result in OLS old version.

> curl 'https://www.ebi.ac.uk/ols/api/ontologies/GAZ/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGAZ_00240693' \
>   -H 'Accept: application/json' \
>   --compressed

**Comment by henrietteharmse** [comment]
Related to #542

**Comment by henrietteharmse** [comment]
The issue here is that `GAZ:00240693` is an individual and not a class/term. Hence to call this correctly, the call must look as follows: [https://www.ebi.ac.uk/ols4/api/ontologies/GAZ/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGAZ_00240693](https://www.ebi.ac.uk/ols4/api/ontologies/GAZ/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGAZ_00240693).

Why is this "working" in OLS3? Individuals have been added much later to OLS3. It is possible that it has been missed that this is in fact an individual. This is a bug in OLS3.

**Comment by henrietteharmse** [comment]
Seems to have been broken by this [commit](db89e19c48b6e4eefbebd2f0e8b96fe4a2420c41).

**Comment by henrietteharmse** [comment]
Currently this is working as expected. See [https://www.ebi.ac.uk/ols4/api/ontologies/GAZ/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGAZ_00240693]( https://www.ebi.ac.uk/ols4/api/ontologies/GAZ/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGAZ_00240693).
