### ISSUE TITLE
PCL is no longer in OLS4

### ISSUE THREAD

**Issue by aleixpuigb** [EBISPOT/ols4#607]
**Describe the problem**
PCL does no longer appear in OLS4, and only the terms that have been imported to CCF are visible. IRI of any PCL term takes directly to OLS4 homepage.

Example of a term:
[Imported in CCF](https://www.ebi.ac.uk/ols4/ontologies/ccf/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPCL_0015001)
PCL IRI: http://purl.obolibrary.org/obo/PCL_0015001

**Screenshots**
![image](https://github.com/EBISPOT/ols4/assets/94959119/636fb721-d474-4f1e-a94e-dca1e6566a9f)

**Comment by henrietteharmse** [comment]
To help PCL to get more quickly onto OLS, it was added to the EBI OLS config rather than waiting for it become available on OBO. When PCL became available on OBO, it was never removed from the EBI OLS config. Subsequently OBO moved the location of the `ontology_purl`, while the EBI OLS config for PCL still pointed to the old location.

PCL should be available on OLS by  15 Jan.

**Comment by aleixpuigb** [comment]
Thank you!
