### ISSUE TITLE
Add Animal Health Ontology for Livestock to EBI OLS

### ISSUE THREAD

**Issue by kennybaird** [EBISPOT/ols4#610]
Details as per the attached spreadsheet
``
[New OLS ontology request Animal Health Ontology for Livestock .xlsx](https://github.com/EBISPOT/ols4/files/13961253/New.OLS.ontology.request.Animal.Health.Ontology.for.Livestock.xlsx)

**Comment by matentzn** [comment]
@kennybaird 

Can I ask why exactly this ontology should be added to OLS? n particular since you have it on browsable on Bioportal.. From an OBO perspective I would find it a bit concerning as this ontology does not follow any of the best practices, including the absence of an issue tracker, any evidence that it is still maintained, using different PURLs for NCBI taxon classes (http://www.ncbi.nlm.nih.gov/taxonomy/9825), providing no obvious mechanism for syncing with NCBI taxonomy (renaming NCBI taxa even!), having overlap with other more comprehensive ontologies (Mondo for animal diseases, VBO for breeds). My personal opinion is that AHOL should be submitted to OBO and via that route enter OLS - I fear it could be quite confusing at this point to have it in OLS. But even before that it would be good to hear your motivation!

Thank you!

**Comment by kennybaird** [comment]
ah, thanks.  We at Boehringer were asked to ask to add this and 2 other ontologies by internal stakeholders.  I take your points about the governance issues (esp the renaming).   We will go down the route you suggest.  Thanks,
Kenny

**Comment by matentzn** [comment]
I think you would be better off relying on https://ols.monarchinitiative.org/ontologies/vbo for breeds and https://ols.monarchinitiative.org/ontologies/mondo for diseases in the long term!
