### ISSUE TITLE
Ontologies load failure - OLS4

### ISSUE THREAD

**Issue by deepananbu** [EBISPOT/ols4#671]
We are facing multiple issues while loading ontologies through OLS4. Below are the issues

| OntologyId  | Issue | Exception |
| ------------- | ------------- | ------------- |
| abcd  | Invalid URI  | org.apache.jena.riot.RiotException: Bad character in IRI (space): <http://rs.tdwg.org/abcd/terms/Specimen[space]...> |
| battinfo  | URL doesn't exist  | org.apache.jena.riot.RiotNotFoundException: Not found: https://w3id.org/emmo/domain/battery/0.8.0-beta/battery |
| bdsubj  | Content Type  | org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=https://purl.org/fidbaudigital/subjects : stream=text/plain) |
| peco  | Content  | org.apache.jena.riot.RiotException: [line: 1, col: 1 ] Content is not allowed in prolog. |
| hoom  | Multiple Children  | org.apache.jena.riot.RiotException: [line: 21, col: 74] {E201} Multiple children of property element |

These ontologies are loaded successfully in OLS3. Is there a way/approach we can follow to load these ontologies in OLS4?

**Comment by haideriqbal** [comment]
Hi @deepananbu, looking at the table you have provided I can see the majority of the issues you are facing are because of the format of the ontologies.

OLS4 only accepts ontologies which are in RDF/OWL format so this the ontology itself and all the imports need to be RDF format. If for example the ontology itself is not in RDF format or one of its import is not in RDF format then OLS would complain.

Just a note, PECO is already in OLS4 you can access it here: https://www.ebi.ac.uk/ols4/ontologies/peco

**Comment by deepananbu** [comment]
@haideriqbal - Do we have any workaround or temp solution to load these ontologies in OLS4? And what would be ideal solution to fix these kind of issues?

**Comment by haideriqbal** [comment]
@deepananbu possible fix would be to convert your ontologies to RDF format. You can do this using protoge (https://protege.stanford.edu/) or robot (https://robot.obolibrary.org/)

**Comment by yangyangmiao2019** [comment]
http://www.ebi.ac.uk/efo/EFO_0009603 请问 这个数据如何下载？急，请求帮助。

**Comment by henrietteharmse** [comment]
@deepananbu I am closing this ticket for now as to the best of our knowledge this needs to be fixed on your side. Please feel free to open this again if this proves otherwise.
